name: count_diff_exclude_batch
description: diff-count
outputs:
  diff-count:
    value: ${{ steps.diff.outputs.diff-count }}
runs:
  using: composite
  steps:
    - id: diff
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
      run: |
        git fetch origin ${TARGET_BRANCH}
        count=`git diff origin/main --name-only ':(exclude)cmd/*'  | wc -l`
        echo "::set-output name=diff-count::$(echo $count)"
      shell: bash