name: count_diff_exclude_cmd
description: count_diff_exclude_cmd
outputs:
  count:
    description: number of git diff exclude cmd/*
    value: ${{ steps.diff.outputs.count }}
  hello:
    description: test str
    value: ${{ steps.diff.outputs.hello}}
runs:
  using: composite
  steps:
    - id: diff
      run: |
        count=`git diff origin/main --name-only ':(exclude)cmd/*'  | wc -l`
        echo $count
        echo "::set-output name=count::$(echo $count)"
        echo "::set-output name=hello::hello"
      shell: bash