name: deployment

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "README.md"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_source
        uses: actions/checkout@v2
      - name: count_diff_exclude_batch
        uses: ./.github/composite/diff
        id: diff
      #   id: diff
      - name: run cmd
        run: echo {steps.count_diff_exclude_batch.outputs.diff-count}