name: deployment

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "README.md"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 
      - uses: .github/composite/diff
        name: Count diff
        id: diff
      - name: run cmd
        run: echo {steps.diff.outputs.diff-count}